title: Beehivecell
description: "MITRE&ATTACK LIBRARY"
author:
  name: "Beehivecell"
  email: "info@beehivecell.com"
  url: "https://beehivecell.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Beehivecell"
year : "2025"
google_analytics: "G-JBB4RB1MK3"
